# Default icon mappings
# You can define your own icons by creating a file of the same format at
# ~/.config/niri/autoname-workspaces.toml

# Default icon for applications not in the list below
default = "*"

[matches]
"file-roller" = ""
"firefox-esr" = ""
"gimp-2.8" = ""
"gnome-control-center" = ""
"gnome-terminal-server" = ""
"google-chrome" = ""
"jetbrains-idea" = ""
"jetbrains-studio" = ""
"lua5.1" = ""
"mysql-workbench-bin" = ""
"prusa-slicer" = ""
"slic3r.pl" = ""
"xfce4-terminal" = ""
alacritty = ""
atom = ""
banshee = ""
blender = ""
chromium = ""
cura = ""
darktable = ""
discord = ""
eclipse = ""
emacs = ""
eog = ""
evince = ""
evolution = ""
factorio = ""
feh = ""
filezilla = ""
firefox = ""
foot = ""
gimp = ""
gpick = ""
imv = ""
insomnia = ""
java = ""
keepassxc = ""
keybase = ""
kicad = ""
kitty = ""
libreoffice = ""
mpv = ""
mupdf = ""
nautilus = ""
nemo = ""
openscad = ""
pavucontrol = ""
postman = ""
rhythmbox = ""
robo3t = ""
signal = ""
slack = ""
spotify = ""
steam = ""
subl = ""
subl3 = ""
sublime_text = ""
thunar = ""
thunderbird = ""
totem = ""
urxvt = ""
xournal = ""
yelp = ""
zenity = ""
zoom = ""
